apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spce:
  project: default

  source: 
    repoURL: https://github.com/dudi938/k8s_nginx.git
    targetRevision: HEAD
    path: templates
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

